name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: set up JDK 8
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '8'
    #     distribution: 'adopt'
    #     cache: gradle

#     - name: Install NDK 21
#       run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=/usr/local/lib/android/sdk/
      
    - name: Download NDK 21
      run: |
        wget --quiet --output-document=android-ndk.zip "http://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip"
        rm -rf /usr/local/lib/android/sdk/ndk/23.0.7599858/
        mkdir /usr/local/lib/android/sdk/ndk/23.0.7599858/
        unzip -q android-ndk.zip
        ls
        # cp -a /android-ndk-r21d/ /usr/local/lib/android/sdk/ndk/23.0.7599858/
        # ls /usr/local/lib/android/sdk/ndk/23.0.7599858/
      
#     - name: Install rust dependencies
#       run: rustup target add armv7-linux-androideabi | rustup target add aarch64-linux-android | rustup target add i686-linux-android | rustup target add x86_64-linux-android | rustup target add x86_64-unknown-linux-gnu

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
    #- name: Build with Gradle
      #run: ./gradlew build --stacktrace
